# Path to your dotfile directory containing this config file (relative to $HOME) is: core/areas/external

[settings]
default_target_type = "symbolic"

[mango.files]
"mango" = "~/.config/mango/"

[kanata.files]
"kanata" = "~/.config/kanata"

[ghostty.files]
"ghostty" = "~/.config/ghostty"

[walls.files]
"walls/wall.gif" = "~/wall.gif"
"walls/.current_wallpaper.png" = "~/.current_wallpaper.png"
"walls/wall.png" = "~/wall.png"

# [makima.files]
# "makima" = "~/.config/makima"

[direnv.files]
"misc/direnv.toml" = "~/.config/direnv/direnv.toml"

[rofi.files]
"rofi" = "~/.config/rofi"

[hyprland.files]
"hyprland" = "~/.config/hypr"

[noctalia.files]
"noctalia" = "~/.config/noctalia"

[just.files]
"just" = "~/.config/just"

[fish.files]
"fish/functions/mkcd.fish" = "~/.config/fish/functions/mkcd.fish"

[kde.files]
"kde/kdeglobals" = "~/.config/kdeglobals"

[nix-init.files]
"nix-init/config.toml" = "~/.config/nix-init/config.toml"

[vale.files]
"vale/.vale.ini" = "~/.config/vale/.vale.ini"

[prettypst.files]
"prettypst/prettypst.toml" = "~/.config/prettypst/prettypst.toml"

[bundle]
depends = [
		"kanata",
		"ghostty",
		"walls",
		"direnv",
		"rofi",
		"mango",
		"hyprland",
		"noctalia",
		"just",
		"fish",
        "kde",
        "nix-init",
        "vale",
        "prettypst"
] # DONT FORGET TO UPDATE THESE!!!!!!!!!!!
