dotfiles_dir = "core/areas/external" # Path to your dotfile directory containing this config file (relative to $HOME). 

[profiles.kanata.dots]
kanata = {source = "kanata", target = ".config/kanata"}

[profiles.ghostty.dots]
ghostty = {source = "ghostty", target = ".config/ghostty"}


[profiles.walls.dots]
wallgif = {source = "walls/wall.gif", target = "~/wall.gif"}
wallstylix = {source = "walls/.current_wallpaper.png", target = "~/.current_wallpaper.png"}

[profiles.bundle]
extra_profiles = ["kanata", "ghostty", "walls"]
